[package]
name = "msc-infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
ed25519-dalek = "2"
msc-domain = { path = "../msc-domain" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
ureq = "3"
zip = { version = "8.6.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
flate2 = "1"
rusty-leveldb = "4.0.1"
tar = "0.4"

fastnbt = "2"
fs2 = "0.4"
png = "0.18"
toml = "0.9"
regex = "1"
uuid = { version = "1.24.0", features = ["v4"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
